# Generated by rust2rpm 27

Patch1: compiletest_rs-fix-metadata.diff
%bcond check 1
%global debug_package %{nil}

%global crate compiletest_rs

Name:           rust-compiletest_rs
Version:        0.11.2
Release:        %autorelease
Summary:        Compiletest utility from the Rust compiler as a standalone testing harness

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/compiletest_rs
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          compiletest_rs-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The compiletest utility from the Rust compiler as a standalone testing
harness.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustc-devel %{_description}

This package contains library source intended for building other packages which
use the "rustc" feature of the "%{crate}" crate.

%files       -n %{name}+rustc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stable-devel %{_description}

This package contains library source intended for building other packages which
use the "stable" feature of the "%{crate}" crate.

%files       -n %{name}+stable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tempfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tempfile-devel %{_description}

This package contains library source intended for building other packages which
use the "tempfile" feature of the "%{crate}" crate.

%files       -n %{name}+tempfile-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tmp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tmp-devel %{_description}

This package contains library source intended for building other packages which
use the "tmp" feature of the "%{crate}" crate.

%files       -n %{name}+tmp-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
